table dim_date
	lineageTag: 803f0728-ad62-4370-95b5-0cc9be69eaf0

	measure 'Matches' = DISTINCTCOUNT(dim_match[match_id])
		formatString: #,##0
		displayFolder: Executive
		lineageTag: fb0ac179-9645-5a33-99cf-434b51863901

	measure 'Participant Rows' = COUNTROWS(fact_participant_performance)
		formatString: #,##0
		displayFolder: Executive
		lineageTag: d16ef8b6-e45d-5060-82ec-7c16bbcb55ef

	measure 'Unique Players' = DISTINCTCOUNT(dim_summoner[puuid])
		formatString: #,##0
		displayFolder: Executive
		lineageTag: 54de0b1c-2850-51c4-ac6c-930ceee15db8

	measure 'Unique Champions' = DISTINCTCOUNT(dim_champion[champion_id])
		formatString: #,##0
		displayFolder: Executive
		lineageTag: 0f81fda2-65e1-5be4-8a7e-1744c688d209

	measure 'Participant Wins' =
			CALCULATE(
			    COUNTROWS(fact_participant_performance),
			    fact_participant_performance[win] = TRUE()
			)
		formatString: #,##0
		displayFolder: Executive
		lineageTag: 5f6e7a80-7b81-52af-96c3-81017c4b3b4d

	measure 'Participant Win Rate' = DIVIDE([Participant Wins], [Participant Rows])
		formatString: 0.0%
		displayFolder: Executive
		lineageTag: dcb956e5-6b1f-5a78-b079-c04136db3c74

	measure 'Avg KDA' = AVERAGE(fact_participant_performance[kda])
		formatString: 0.00
		displayFolder: Executive
		lineageTag: c2a46467-491c-5bc8-94fc-672d85380b1c

	measure 'Avg Match Duration Minutes' = DIVIDE(AVERAGE(dim_match[game_duration]), 60)
		formatString: 0.00
		displayFolder: Executive
		lineageTag: 91411a59-38a5-59d1-aafb-0808afbf5456

	measure 'Total Kills' = SUM(fact_participant_performance[kills])
		formatString: #,##0
		displayFolder: Executive
		lineageTag: ab2ae426-f6d6-5c0e-9cf4-ff4c18fd63da

	measure 'Total Deaths' = SUM(fact_participant_performance[deaths])
		formatString: #,##0
		displayFolder: Executive
		lineageTag: 4d5f81a7-4b6f-5899-a6fa-e18a8028b33f

	measure 'Total Assists' = SUM(fact_participant_performance[assists])
		formatString: #,##0
		displayFolder: Executive
		lineageTag: 6f6863fc-b041-5712-bdb5-2f385783a26c

	measure 'Avg Gold Earned' = AVERAGE(fact_participant_performance[gold_earned])
		formatString: 0.00
		displayFolder: Executive
		lineageTag: 46fdde84-b9e3-56eb-a995-e0290f2a8158

	measure 'Avg Damage To Champions' = AVERAGE(fact_participant_performance[total_damage_dealt_to_champions])
		formatString: 0.00
		displayFolder: Executive
		lineageTag: b59fdd30-92c9-54d8-9bd8-0360aedbf4fb

	measure 'Avg Vision Score' = AVERAGE(fact_participant_performance[vision_score])
		formatString: 0.00
		displayFolder: Executive
		lineageTag: 094ed413-63e5-5c14-b6b0-2c7b2a4d54aa

	measure 'Avg CS' = AVERAGE(fact_participant_performance[cs])
		formatString: 0.00
		displayFolder: Executive
		lineageTag: a83ba330-f929-54e1-b347-43f24957c1f6

	measure 'Player Matches' = SUM(mart_player_daily_performance[matches_played])
		formatString: #,##0
		displayFolder: Player
		lineageTag: 96dfaa34-fb86-53c0-b7a8-e1e8d3ec5a35

	measure 'Player Wins' = SUM(mart_player_daily_performance[wins])
		formatString: #,##0
		displayFolder: Player
		lineageTag: 09c34993-a87a-55e8-8be0-f3d3de0fb58d

	measure 'Player Losses' = SUM(mart_player_daily_performance[losses])
		formatString: #,##0
		displayFolder: Player
		lineageTag: 49da4a60-a01a-5781-8122-4f4c1926b7ec

	measure 'Player Win Rate' = DIVIDE([Player Wins], [Player Matches])
		formatString: 0.0%
		displayFolder: Player
		lineageTag: 21e3d65b-9455-549a-84a5-e9cf3697c5dd

	measure 'Player Total Kills' = SUM(mart_player_daily_performance[total_kills])
		formatString: #,##0
		displayFolder: Player
		lineageTag: cf0d59fb-66cb-5674-98d5-a63a2e2dfe3d

	measure 'Player Total Deaths' = SUM(mart_player_daily_performance[total_deaths])
		formatString: #,##0
		displayFolder: Player
		lineageTag: 0320dd63-1bf6-5dbd-97fe-267c9e0d022c

	measure 'Player Total Assists' = SUM(mart_player_daily_performance[total_assists])
		formatString: #,##0
		displayFolder: Player
		lineageTag: 5dbfa58a-563a-5998-8e4a-3f8802f8c889

	measure 'Player KDA Ratio' =
			DIVIDE(
			    [Player Total Kills] + [Player Total Assists],
			    [Player Total Deaths]
			)
		formatString: 0.00
		displayFolder: Player
		lineageTag: d2f681b5-753b-56f8-8772-56166210e0fe

	measure 'Player Avg KDA' =
			DIVIDE(
			    SUMX(
			        mart_player_daily_performance,
			        mart_player_daily_performance[avg_kda] * mart_player_daily_performance[matches_played]
			    ),
			    [Player Matches]
			)
		formatString: 0.00
		displayFolder: Player
		lineageTag: 69e9b5e3-a5fc-5da3-8794-22bf6237c9cb

	measure 'Player Avg Gold Earned' =
			DIVIDE(
			    SUMX(
			        mart_player_daily_performance,
			        mart_player_daily_performance[avg_gold_earned] * mart_player_daily_performance[matches_played]
			    ),
			    [Player Matches]
			)
		formatString: 0.00
		displayFolder: Player
		lineageTag: c8465d6c-e8fd-55ed-b1de-05e7ac9ca60d

	measure 'Player Avg Damage To Champions' =
			DIVIDE(
			    SUMX(
			        mart_player_daily_performance,
			        mart_player_daily_performance[avg_damage_dealt_to_champions] * mart_player_daily_performance[matches_played]
			    ),
			    [Player Matches]
			)
		formatString: 0.00
		displayFolder: Player
		lineageTag: 8f4c2a44-2047-511c-8c83-ad80467f3f90

	measure 'Player Avg Vision Score' =
			DIVIDE(
			    SUMX(
			        mart_player_daily_performance,
			        mart_player_daily_performance[avg_vision_score] * mart_player_daily_performance[matches_played]
			    ),
			    [Player Matches]
			)
		formatString: 0.00
		displayFolder: Player
		lineageTag: 6a80172c-498a-570a-8c20-bf1711c286a6

	measure 'Player Avg CS' =
			DIVIDE(
			    SUMX(
			        mart_player_daily_performance,
			        mart_player_daily_performance[avg_cs] * mart_player_daily_performance[matches_played]
			    ),
			    [Player Matches]
			)
		formatString: 0.00
		displayFolder: Player
		lineageTag: e70f5329-5f91-5440-9cfb-88ff7fc5a5d5

	measure 'Player Unique Champions' = MAX(mart_player_daily_performance[unique_champions])
		formatString: #,##0
		displayFolder: Player
		lineageTag: 3bbf026a-c4c5-5265-bbf6-c47983824b6a

	measure 'Champion Matches' = SUM(mart_champion_daily_performance[matches_played])
		formatString: #,##0
		displayFolder: Champion
		lineageTag: 2b19c245-6e17-5de1-89e6-0722e9ad544b

	measure 'Champion Unique Players' = SUM(mart_champion_daily_performance[unique_players])
		formatString: #,##0
		displayFolder: Champion
		lineageTag: e76b7057-23eb-5440-aa72-fc115681eea0

	measure 'Champion Wins' = SUM(mart_champion_daily_performance[wins])
		formatString: #,##0
		displayFolder: Champion
		lineageTag: 9649c23e-4ad6-56e1-946a-a45ce1b07eee

	measure 'Champion Losses' = SUM(mart_champion_daily_performance[losses])
		formatString: #,##0
		displayFolder: Champion
		lineageTag: 2cb55fe2-8661-5297-b7d0-4f0b3663821f

	measure 'Champion Win Rate' = DIVIDE([Champion Wins], [Champion Matches])
		formatString: 0.0%
		displayFolder: Champion
		lineageTag: f0c28bb5-4d59-581c-af0d-e8c856602609

	measure 'Champion Pick Rate' =
			DIVIDE(
			    [Champion Matches],
			    CALCULATE(
			        [Champion Matches],
			        REMOVEFILTERS(dim_champion)
			    )
			)
		formatString: 0.0%
		displayFolder: Champion
		lineageTag: d298094d-d5fc-5c7e-98f6-b43d2adbe5c8

	measure 'Champion Total Kills' = SUM(mart_champion_daily_performance[total_kills])
		formatString: #,##0
		displayFolder: Champion
		lineageTag: d3010108-0216-51c5-99c6-acb7871df39b

	measure 'Champion Total Deaths' = SUM(mart_champion_daily_performance[total_deaths])
		formatString: #,##0
		displayFolder: Champion
		lineageTag: af325163-021d-5519-b645-5c3a0aa41bf0

	measure 'Champion Total Assists' = SUM(mart_champion_daily_performance[total_assists])
		formatString: #,##0
		displayFolder: Champion
		lineageTag: 55b20335-0981-5713-bd5e-c451ed55e77d

	measure 'Champion Avg KDA' =
			DIVIDE(
			    SUMX(
			        mart_champion_daily_performance,
			        mart_champion_daily_performance[avg_kda] * mart_champion_daily_performance[matches_played]
			    ),
			    [Champion Matches]
			)
		formatString: 0.00
		displayFolder: Champion
		lineageTag: 1220a2f4-dca6-51a3-9bff-9873ac2a4214

	measure 'Champion Avg Gold Earned' =
			DIVIDE(
			    SUMX(
			        mart_champion_daily_performance,
			        mart_champion_daily_performance[avg_gold_earned] * mart_champion_daily_performance[matches_played]
			    ),
			    [Champion Matches]
			)
		formatString: 0.00
		displayFolder: Champion
		lineageTag: 42a529d1-3b8f-52ef-afba-1f3070f4d46d

	measure 'Champion Avg Damage To Champions' =
			DIVIDE(
			    SUMX(
			        mart_champion_daily_performance,
			        mart_champion_daily_performance[avg_damage_dealt_to_champions] * mart_champion_daily_performance[matches_played]
			    ),
			    [Champion Matches]
			)
		formatString: 0.00
		displayFolder: Champion
		lineageTag: 28abf183-56d7-5589-8f4c-9e8dad6a30cb

	measure 'Champion Avg Vision Score' =
			DIVIDE(
			    SUMX(
			        mart_champion_daily_performance,
			        mart_champion_daily_performance[avg_vision_score] * mart_champion_daily_performance[matches_played]
			    ),
			    [Champion Matches]
			)
		formatString: 0.00
		displayFolder: Champion
		lineageTag: 5f02a0f2-774a-5fe9-99d8-80c0093dfc31

	measure 'Champion Avg CS' =
			DIVIDE(
			    SUMX(
			        mart_champion_daily_performance,
			        mart_champion_daily_performance[avg_cs] * mart_champion_daily_performance[matches_played]
			    ),
			    [Champion Matches]
			)
		formatString: 0.00
		displayFolder: Champion
		lineageTag: e5f037d4-2077-557c-af4f-d316938f0be8

	measure 'Champion Damage Share' =
			DIVIDE(
			    [Champion Avg Damage To Champions],
			    CALCULATE(
			        [Champion Avg Damage To Champions],
			        REMOVEFILTERS(dim_champion)
			    )
			)
		formatString: 0.0%
		displayFolder: Champion
		lineageTag: 01e05247-36ee-5e6e-b336-656ec7bfac2f

	measure 'Champion Meta Score' = ([Champion Win Rate] * 0.5) + ([Champion Pick Rate] * 0.3) + (DIVIDE([Champion Avg KDA], 10) * 0.2)
		formatString: 0.00
		displayFolder: Champion
		lineageTag: 471a7de9-4c41-5f7f-b9b8-b272353a608b

	measure 'Role Matches' = SUM(mart_role_daily_performance[matches_played])
		formatString: #,##0
		displayFolder: Role
		lineageTag: 6a405ae6-2e10-5391-9671-090ef17b6996

	measure 'Role Wins' = SUM(mart_role_daily_performance[wins])
		formatString: #,##0
		displayFolder: Role
		lineageTag: c81bfaa1-c228-5a35-928e-9ddb8fa62d03

	measure 'Role Losses' = SUM(mart_role_daily_performance[losses])
		formatString: #,##0
		displayFolder: Role
		lineageTag: 6b6ec9ad-cffd-562f-b9fd-0614dab8cab4

	measure 'Role Win Rate' = DIVIDE([Role Wins], [Role Matches])
		formatString: 0.0%
		displayFolder: Role
		lineageTag: 30a81f15-b8e7-596a-a851-8432ab9c69e7

	measure 'Role Avg Kills' =
			DIVIDE(
			    SUMX(
			        mart_role_daily_performance,
			        mart_role_daily_performance[avg_kills] * mart_role_daily_performance[matches_played]
			    ),
			    [Role Matches]
			)
		formatString: 0.00
		displayFolder: Role
		lineageTag: 4e38a681-9cfc-5821-93d0-55a712e16906

	measure 'Role Avg Deaths' =
			DIVIDE(
			    SUMX(
			        mart_role_daily_performance,
			        mart_role_daily_performance[avg_deaths] * mart_role_daily_performance[matches_played]
			    ),
			    [Role Matches]
			)
		formatString: 0.00
		displayFolder: Role
		lineageTag: 9bc0d9a2-69cd-5359-a697-e76d8353b7fc

	measure 'Role Avg Assists' =
			DIVIDE(
			    SUMX(
			        mart_role_daily_performance,
			        mart_role_daily_performance[avg_assists] * mart_role_daily_performance[matches_played]
			    ),
			    [Role Matches]
			)
		formatString: 0.00
		displayFolder: Role
		lineageTag: 48db016c-9d42-5c7d-b3b4-f2c5c6174e96

	measure 'Role Avg KDA' =
			DIVIDE(
			    SUMX(
			        mart_role_daily_performance,
			        mart_role_daily_performance[avg_kda] * mart_role_daily_performance[matches_played]
			    ),
			    [Role Matches]
			)
		formatString: 0.00
		displayFolder: Role
		lineageTag: b0984d77-f42e-5af3-9cc0-1e65667c1142

	measure 'Role Avg Gold Earned' =
			DIVIDE(
			    SUMX(
			        mart_role_daily_performance,
			        mart_role_daily_performance[avg_gold_earned] * mart_role_daily_performance[matches_played]
			    ),
			    [Role Matches]
			)
		formatString: 0.00
		displayFolder: Role
		lineageTag: 99b80b12-adf0-58ca-9902-89a113e8871e

	measure 'Role Avg Damage To Champions' =
			DIVIDE(
			    SUMX(
			        mart_role_daily_performance,
			        mart_role_daily_performance[avg_damage_dealt_to_champions] * mart_role_daily_performance[matches_played]
			    ),
			    [Role Matches]
			)
		formatString: 0.00
		displayFolder: Role
		lineageTag: 1d456835-9a7c-50a9-9424-4256d1cc3d70

	measure 'Role Avg Vision Score' =
			DIVIDE(
			    SUMX(
			        mart_role_daily_performance,
			        mart_role_daily_performance[avg_vision_score] * mart_role_daily_performance[matches_played]
			    ),
			    [Role Matches]
			)
		formatString: 0.00
		displayFolder: Role
		lineageTag: 682bb805-c8cf-54df-8c67-f11f51509189

	measure 'Role Avg CS' =
			DIVIDE(
			    SUMX(
			        mart_role_daily_performance,
			        mart_role_daily_performance[avg_cs] * mart_role_daily_performance[matches_played]
			    ),
			    [Role Matches]
			)
		formatString: 0.00
		displayFolder: Role
		lineageTag: 8d869342-e1ce-534f-838b-ea9b9caee167

	measure 'Rank Summary Players' = SUM(mart_rank_daily_summary[players])
		formatString: #,##0
		displayFolder: Rank
		lineageTag: bff72c4f-e3a9-5f9a-9a14-651b6fde90d0

	measure 'Rank Avg League Points' =
			DIVIDE(
			    SUMX(
			        mart_rank_daily_summary,
			        mart_rank_daily_summary[avg_league_points] * mart_rank_daily_summary[players]
			    ),
			    [Rank Summary Players]
			)
		formatString: 0.00
		displayFolder: Rank
		lineageTag: 2362e2e8-5d9f-5963-a8c6-b71edcae9b93

	measure 'Rank Total Wins' = SUM(mart_rank_daily_summary[total_wins])
		formatString: #,##0
		displayFolder: Rank
		lineageTag: 7c4ab3b0-aac9-5afe-ac89-984d682fc3d3

	measure 'Rank Total Losses' = SUM(mart_rank_daily_summary[total_losses])
		formatString: #,##0
		displayFolder: Rank
		lineageTag: 3b445861-6866-5842-9b24-8981f0a9d106

	measure 'Rank Avg Win Rate' =
			DIVIDE(
			    [Rank Total Wins],
			    [Rank Total Wins] + [Rank Total Losses]
			)
		formatString: 0.0%
		displayFolder: Rank
		lineageTag: 35d97fe4-a4af-5509-8530-2b91609b63e0

	measure 'Hot Streak Players' = SUM(mart_rank_daily_summary[hot_streak_players])
		formatString: #,##0
		displayFolder: Rank
		lineageTag: 1e2d4c4d-798b-5a3e-9113-9588f0fcfe9a

	measure 'Veteran Players' = SUM(mart_rank_daily_summary[veteran_players])
		formatString: #,##0
		displayFolder: Rank
		lineageTag: 8dd53191-f1ba-5ccd-a429-5fe0e9fd54c7

	measure 'Fresh Blood Players' = SUM(mart_rank_daily_summary[fresh_blood_players])
		formatString: #,##0
		displayFolder: Rank
		lineageTag: 17c1e990-4203-5d1d-a7cc-95c1fd0cd587

	measure 'Inactive Players' = SUM(mart_rank_daily_summary[inactive_players])
		formatString: #,##0
		displayFolder: Rank
		lineageTag: be0e61e1-306f-55f1-af91-c83c810ab481

	measure 'Rank Population Share' =
			DIVIDE(
			    [Rank Summary Players],
			    CALCULATE(
			        [Rank Summary Players],
			        REMOVEFILTERS(mart_rank_daily_summary[tier]),
			        REMOVEFILTERS(mart_rank_daily_summary[rank])
			    )
			)
		formatString: 0.0%
		displayFolder: Rank
		lineageTag: c5ec29a9-b4c4-544d-81d1-534acfb39952

	measure 'Team Objective Games' = SUM(mart_team_objective_daily_summary[games_played])
		formatString: #,##0
		displayFolder: "Team Objectives"
		lineageTag: 6dd6e40f-a76a-5088-bbbc-05d05051117c

	measure 'Team Objective Wins' = SUM(mart_team_objective_daily_summary[wins])
		formatString: #,##0
		displayFolder: "Team Objectives"
		lineageTag: ccb86448-455e-52d3-b16a-dca9458bb024

	measure 'Team Objective Losses' = SUM(mart_team_objective_daily_summary[losses])
		formatString: #,##0
		displayFolder: "Team Objectives"
		lineageTag: 06c25245-af95-55c3-90be-d28486e14789

	measure 'Team Win Rate' = DIVIDE([Team Objective Wins], [Team Objective Games])
		formatString: 0.0%
		displayFolder: "Team Objectives"
		lineageTag: f4a4467b-b2f9-5989-a48a-65494b0909ba

	measure 'Avg Objective Score' =
			DIVIDE(
			    SUMX(
			        mart_team_objective_daily_summary,
			        mart_team_objective_daily_summary[avg_objective_score] * mart_team_objective_daily_summary[games_played]
			    ),
			    [Team Objective Games]
			)
		formatString: 0.00
		displayFolder: "Team Objectives"
		lineageTag: 6b0d27e9-7caf-5797-a3e3-fe02cff7f33a

	measure 'Total Dragon Kills' = SUM(fact_team_objectives[dragon_kills])
		formatString: #,##0
		displayFolder: "Team Objectives"
		lineageTag: eecc10d2-e3f2-5f28-8e4e-41d731fc5e36

	measure 'Total Baron Kills' = SUM(fact_team_objectives[baron_kills])
		formatString: #,##0
		displayFolder: "Team Objectives"
		lineageTag: f442ae6d-2708-5393-aeda-0ee0d831ac6d

	measure 'Total Rift Herald Kills' = SUM(fact_team_objectives[rift_herald_kills])
		formatString: #,##0
		displayFolder: "Team Objectives"
		lineageTag: d0ea6dca-50b7-573f-9828-bcd11c1ccf29

	measure 'Total Tower Kills' = SUM(fact_team_objectives[tower_kills])
		formatString: #,##0
		displayFolder: "Team Objectives"
		lineageTag: 73fbcc9f-520c-54e5-9cdc-b91eeeb042ee

	measure 'Total Inhibitor Kills' = SUM(fact_team_objectives[inhibitor_kills])
		formatString: #,##0
		displayFolder: "Team Objectives"
		lineageTag: 4d589cc1-c7a6-59d0-a4f9-c3ff3437ce22

	measure 'Total Objective Score' = SUM(fact_team_objectives[objective_score])
		formatString: #,##0
		displayFolder: "Team Objectives"
		lineageTag: ac82956d-c137-5602-80bc-91c1b7e68ccb

	measure 'Timeline Events' = COUNTROWS(fact_timeline_events)
		formatString: #,##0
		displayFolder: Timeline
		lineageTag: 4b275f29-7c01-56b9-a447-c017e55a4971

	measure 'Avg Events Per Match' =
			DIVIDE(
			    [Timeline Events],
			    DISTINCTCOUNT(fact_timeline_events[match_id])
			)
		formatString: 0.00
		displayFolder: Timeline
		lineageTag: 5fce9f4c-63d1-5e43-aa24-5f9684b205c3

	measure 'Average Event Minute' = DIVIDE(AVERAGE(fact_timeline_events[event_timestamp]), 60000)
		formatString: 0.00
		displayFolder: Timeline
		lineageTag: 31366172-fb93-5514-b060-e13d8073169b

	measure 'Events Before 15 Minutes' =
			CALCULATE(
			    [Timeline Events],
			    fact_timeline_events[event_timestamp] <= 900000
			)
		formatString: #,##0
		displayFolder: Timeline
		lineageTag: 5c97a22b-cbad-5ff9-ae61-b23e58e13f1a

	measure 'Kills Before 15 Minutes' =
			CALCULATE(
			    [Timeline Events],
			    fact_timeline_events[event_type] = "CHAMPION_KILL",
			    fact_timeline_events[event_timestamp] <= 900000
			)
		formatString: #,##0
		displayFolder: Timeline
		lineageTag: d5f0bcd9-35ff-5d26-9a58-c2dfda746f8b

	measure 'Dragon Events' =
			CALCULATE(
			    [Timeline Events],
			    fact_timeline_events[monster_type] = "DRAGON"
			)
		formatString: #,##0
		displayFolder: Timeline
		lineageTag: f3f5196c-7efc-522d-a582-59acfd26b8b2

	measure 'Baron Events' =
			CALCULATE(
			    [Timeline Events],
			    fact_timeline_events[monster_type] = "BARON_NASHOR"
			)
		formatString: #,##0
		displayFolder: Timeline
		lineageTag: 1989c8d7-eb1e-540d-9a67-9655d6c15a14

	measure 'Tower Events' =
			CALCULATE(
			    [Timeline Events],
			    fact_timeline_events[building_type] = "TOWER_BUILDING"
			)
		formatString: #,##0
		displayFolder: Timeline
		lineageTag: d159edc7-3721-599f-bc7a-a1cf6c1582c9

	measure 'Inhibitor Events' =
			CALCULATE(
			    [Timeline Events],
			    fact_timeline_events[building_type] = "INHIBITOR_BUILDING"
			)
		formatString: #,##0
		displayFolder: Timeline
		lineageTag: 03c8d1ec-607b-5b56-b37e-92d2848b4f46

	column date_key
		dataType: string
		lineageTag: f7e9553c-7d22-4684-9437-9813183519d4
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column date_year
		dataType: int64
		formatString: 0
		lineageTag: 58a3a004-20c0-4de7-b061-675afd451010
		summarizeBy: sum
		sourceColumn: date_year

		annotation SummarizationSetBy = Automatic

	column date_month
		dataType: int64
		formatString: 0
		lineageTag: e3062f27-31cd-4879-a9ab-d04dc0b476f4
		summarizeBy: sum
		sourceColumn: date_month

		annotation SummarizationSetBy = Automatic

	column date_day
		dataType: int64
		formatString: 0
		lineageTag: dff93477-754a-43d0-a43c-c4260e2b144d
		summarizeBy: sum
		sourceColumn: date_day

		annotation SummarizationSetBy = Automatic

	column day_of_week
		dataType: int64
		formatString: 0
		lineageTag: 52a46112-270a-4299-8fe1-344b0c29820f
		summarizeBy: sum
		sourceColumn: day_of_week

		annotation SummarizationSetBy = Automatic

	column game_date
		dataType: string
		lineageTag: 33beca93-82ae-49b9-960c-97c9488d425b
		summarizeBy: none
		sourceColumn: game_date

		annotation SummarizationSetBy = Automatic

	partition dim_date = m
		mode: import
		source =
				let
				    Source = Odbc.DataSource("dsn=riot_lakehouse_athena", [HierarchicalNavigation=true]),
				    AwsDataCatalog_Database = Source{[Name="AwsDataCatalog",Kind="Database"]}[Data],
				    riot_lakehouse_Schema = AwsDataCatalog_Database{[Name="riot_lakehouse",Kind="Schema"]}[Data],
				    dim_date_Table = riot_lakehouse_Schema{[Name="dim_date",Kind="Table"]}[Data]
				in
				    dim_date_Table

	annotation PBI_ResultType = Table

