table mart_rank_daily_summary
	lineageTag: fb8b185d-3d1f-4891-9905-991c98f90f16

	measure 'Rank Summary Players' =
			VAR RankFilter =
			    SUMMARIZE(
			        'dim_rank',
			        'dim_rank'[queue],
			        'dim_rank'[tier],
			        'dim_rank'[rank]
			    )
			RETURN
			    CALCULATE(
			        SUM('mart_rank_daily_summary'[players]),
			        TREATAS(
			            RankFilter,
			            'mart_rank_daily_summary'[queue],
			            'mart_rank_daily_summary'[tier],
			            'mart_rank_daily_summary'[rank]
			        )
			    )
		lineageTag: d7bfd0e9-1b71-4887-8dd7-75258fed4cd2

	measure 'Rank Population Share' =
			DIVIDE(
			    [Rank Summary Players],
			    CALCULATE([Rank Summary Players], ALL('dim_rank'))
			)
		lineageTag: cdec7874-2229-453a-bb2d-6c6f6655ee8d

	measure 'Rank Avg League Points' =
			VAR RankFilter =
			    SUMMARIZE(
			        'dim_rank',
			        'dim_rank'[queue],
			        'dim_rank'[tier],
			        'dim_rank'[rank]
			    )
			RETURN
			    CALCULATE(
			        DIVIDE(
			            SUMX(
			                'mart_rank_daily_summary',
			                'mart_rank_daily_summary'[avg_league_points]
			                    * 'mart_rank_daily_summary'[players]
			            ),
			            SUM('mart_rank_daily_summary'[players])
			        ),
			        TREATAS(
			            RankFilter,
			            'mart_rank_daily_summary'[queue],
			            'mart_rank_daily_summary'[tier],
			            'mart_rank_daily_summary'[rank]
			        )
			    )
		lineageTag: a219a1a0-3f03-468a-ac98-327fa0b00d04

	measure 'Rank Avg Win Rate' =
			VAR RankFilter =
			    SUMMARIZE(
			        'dim_rank',
			        'dim_rank'[queue],
			        'dim_rank'[tier],
			        'dim_rank'[rank]
			    )
			RETURN
			    CALCULATE(
			        DIVIDE(
			            SUMX(
			                'mart_rank_daily_summary',
			                'mart_rank_daily_summary'[avg_win_rate]
			                    * 'mart_rank_daily_summary'[players]
			            ),
			            SUM('mart_rank_daily_summary'[players])
			        ),
			        TREATAS(
			            RankFilter,
			            'mart_rank_daily_summary'[queue],
			            'mart_rank_daily_summary'[tier],
			            'mart_rank_daily_summary'[rank]
			        )
			    )
		lineageTag: 29f1d2fd-cc79-42b9-a4e7-4be9ebdb322a

	measure 'Rank Total Wins' =
			VAR RankFilter =
			    SUMMARIZE(
			        'dim_rank',
			        'dim_rank'[queue],
			        'dim_rank'[tier],
			        'dim_rank'[rank]
			    )
			RETURN
			    CALCULATE(
			        SUM('mart_rank_daily_summary'[total_wins]),
			        TREATAS(
			            RankFilter,
			            'mart_rank_daily_summary'[queue],
			            'mart_rank_daily_summary'[tier],
			            'mart_rank_daily_summary'[rank]
			        )
			    )
		lineageTag: 16a98446-a85f-444e-af28-00c96e1cdf05

	measure 'Rank Total Losses' =
			VAR RankFilter =
			    SUMMARIZE(
			        'dim_rank',
			        'dim_rank'[queue],
			        'dim_rank'[tier],
			        'dim_rank'[rank]
			    )
			RETURN
			    CALCULATE(
			        SUM('mart_rank_daily_summary'[total_losses]),
			        TREATAS(
			            RankFilter,
			            'mart_rank_daily_summary'[queue],
			            'mart_rank_daily_summary'[tier],
			            'mart_rank_daily_summary'[rank]
			        )
			    )
		lineageTag: 4f7f4066-f6c1-4b5e-bc01-d6b5e3cdc785

	measure 'Hot Streak Players' =
			VAR RankFilter =
			    SUMMARIZE(
			        'dim_rank',
			        'dim_rank'[queue],
			        'dim_rank'[tier],
			        'dim_rank'[rank]
			    )
			RETURN
			    CALCULATE(
			        SUM('mart_rank_daily_summary'[hot_streak_players]),
			        TREATAS(
			            RankFilter,
			            'mart_rank_daily_summary'[queue],
			            'mart_rank_daily_summary'[tier],
			            'mart_rank_daily_summary'[rank]
			        )
			    )
		lineageTag: 93c0d20d-a02c-4c4c-b07f-d8ae49ce7ae0

	measure 'Veteran Players' =
			VAR RankFilter =
			    SUMMARIZE(
			        'dim_rank',
			        'dim_rank'[queue],
			        'dim_rank'[tier],
			        'dim_rank'[rank]
			    )
			RETURN
			    CALCULATE(
			        SUM('mart_rank_daily_summary'[veteran_players]),
			        TREATAS(
			            RankFilter,
			            'mart_rank_daily_summary'[queue],
			            'mart_rank_daily_summary'[tier],
			            'mart_rank_daily_summary'[rank]
			        )
			    )
		lineageTag: bb06553d-1978-41d9-aed7-19daa6595a8a

	measure 'Fresh Blood Players' =
			VAR RankFilter =
			    SUMMARIZE(
			        'dim_rank',
			        'dim_rank'[queue],
			        'dim_rank'[tier],
			        'dim_rank'[rank]
			    )
			RETURN
			    CALCULATE(
			        SUM('mart_rank_daily_summary'[fresh_blood_players]),
			        TREATAS(
			            RankFilter,
			            'mart_rank_daily_summary'[queue],
			            'mart_rank_daily_summary'[tier],
			            'mart_rank_daily_summary'[rank]
			        )
			    )
		lineageTag: 8a56d86a-2a35-414f-8e8c-9c2310a9a186

	measure 'Inactive Players' =
			VAR RankFilter =
			    SUMMARIZE(
			        'dim_rank',
			        'dim_rank'[queue],
			        'dim_rank'[tier],
			        'dim_rank'[rank]
			    )
			RETURN
			    CALCULATE(
			        SUM('mart_rank_daily_summary'[inactive_players]),
			        TREATAS(
			            RankFilter,
			            'mart_rank_daily_summary'[queue],
			            'mart_rank_daily_summary'[tier],
			            'mart_rank_daily_summary'[rank]
			        )
			    )
		lineageTag: b936b557-5fbe-4b14-9dc5-f90954f3b178

	measure 'Rank Snapshot Unique Players' =
			VAR RankFilter =
			    SUMMARIZE(
			        'dim_rank',
			        'dim_rank'[queue],
			        'dim_rank'[tier],
			        'dim_rank'[rank]
			    )
			RETURN
			    CALCULATE(
			        DISTINCTCOUNT('fact_rank_snapshot'[puuid]),
			        TREATAS(
			            RankFilter,
			            'fact_rank_snapshot'[queue],
			            'fact_rank_snapshot'[tier],
			            'fact_rank_snapshot'[rank]
			        )
			    )
		lineageTag: 7604004f-259d-4225-a938-b7a0cd89c98e

	measure 'Average League Points' =
			VAR RankFilter =
			    SUMMARIZE(
			        'dim_rank',
			        'dim_rank'[queue],
			        'dim_rank'[tier],
			        'dim_rank'[rank]
			    )
			RETURN
			    CALCULATE(
			        AVERAGE('fact_rank_snapshot'[league_points]),
			        TREATAS(
			            RankFilter,
			            'fact_rank_snapshot'[queue],
			            'fact_rank_snapshot'[tier],
			            'fact_rank_snapshot'[rank]
			        )
			    )
		lineageTag: e1f19588-3e10-4458-b0e9-775bed255f71

	measure 'Rank Snapshot Wins' =
			VAR RankFilter =
			    SUMMARIZE(
			        'dim_rank',
			        'dim_rank'[queue],
			        'dim_rank'[tier],
			        'dim_rank'[rank]
			    )
			RETURN
			    CALCULATE(
			        SUM('fact_rank_snapshot'[wins]),
			        TREATAS(
			            RankFilter,
			            'fact_rank_snapshot'[queue],
			            'fact_rank_snapshot'[tier],
			            'fact_rank_snapshot'[rank]
			        )
			    )
		lineageTag: 7b7fae5f-e4e7-45cd-8c05-02c5a9a0f7b2

	measure 'Rank Snapshot Losses' =
			VAR RankFilter =
			    SUMMARIZE(
			        'dim_rank',
			        'dim_rank'[queue],
			        'dim_rank'[tier],
			        'dim_rank'[rank]
			    )
			RETURN
			    CALCULATE(
			        SUM('fact_rank_snapshot'[losses]),
			        TREATAS(
			            RankFilter,
			            'fact_rank_snapshot'[queue],
			            'fact_rank_snapshot'[tier],
			            'fact_rank_snapshot'[rank]
			        )
			    )
		lineageTag: d1c8874e-a161-4820-8059-0a925050820b

	measure 'Rank Snapshot Win Rate' = DIVIDE([Rank Snapshot Wins], [Rank Snapshot Wins] + [Rank Snapshot Losses])
		lineageTag: c5c671ad-bc94-4c2c-8ab8-d5d30970df58

	measure 'Is Hot Streak Count' =
			CALCULATE(
			    [Rank Snapshot Unique Players],
			    'fact_rank_snapshot'[hot_streak] = TRUE()
			)
		lineageTag: 8263b3f4-82a4-4994-a97e-c2c919f735ac

	measure 'Is Inactive Count' =
			CALCULATE(
			    [Rank Snapshot Unique Players],
			    'fact_rank_snapshot'[inactive] = TRUE()
			)
		lineageTag: a23a233b-6c46-4171-9693-7dae90717288

	column queue
		dataType: string
		lineageTag: ce88e8af-a059-4027-8e47-5039fff6801a
		summarizeBy: none
		sourceColumn: queue

		annotation SummarizationSetBy = Automatic

	column tier
		dataType: string
		lineageTag: 18aaf169-6282-42e6-b2b1-939a9f3fdce8
		summarizeBy: none
		sourceColumn: tier

		annotation SummarizationSetBy = Automatic

	column rank
		dataType: string
		lineageTag: 984f59ee-d2d4-4f74-9883-4ef0ef78094b
		summarizeBy: none
		sourceColumn: rank

		annotation SummarizationSetBy = Automatic

	column players
		dataType: int64
		formatString: 0
		lineageTag: 1a06b5e7-c34d-4ea4-9fbf-93744fba1e28
		summarizeBy: sum
		sourceColumn: players

		annotation SummarizationSetBy = Automatic

	column avg_league_points
		dataType: double
		lineageTag: a0b64c5f-0e2a-4cbe-a9f3-bbbc6f97aa11
		summarizeBy: sum
		sourceColumn: avg_league_points

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_wins
		dataType: int64
		formatString: 0
		lineageTag: e4c56ac2-33c9-4b67-b074-f6808fe9d928
		summarizeBy: sum
		sourceColumn: total_wins

		annotation SummarizationSetBy = Automatic

	column total_losses
		dataType: int64
		formatString: 0
		lineageTag: 2924c07e-3938-48df-b7a2-03eac3cea0a7
		summarizeBy: sum
		sourceColumn: total_losses

		annotation SummarizationSetBy = Automatic

	column avg_win_rate
		dataType: double
		lineageTag: 2d850486-d348-443a-8d82-fbfd07b1167c
		summarizeBy: sum
		sourceColumn: avg_win_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column hot_streak_players
		dataType: int64
		formatString: 0
		lineageTag: 298ff6ea-61f4-4d55-b098-dfe5d7083b5e
		summarizeBy: sum
		sourceColumn: hot_streak_players

		annotation SummarizationSetBy = Automatic

	column veteran_players
		dataType: int64
		formatString: 0
		lineageTag: c7c05779-78c2-4778-8d89-f64719a7aa24
		summarizeBy: sum
		sourceColumn: veteran_players

		annotation SummarizationSetBy = Automatic

	column fresh_blood_players
		dataType: int64
		formatString: 0
		lineageTag: 923179f8-3f5e-4d1b-9bef-163734f4b660
		summarizeBy: sum
		sourceColumn: fresh_blood_players

		annotation SummarizationSetBy = Automatic

	column inactive_players
		dataType: int64
		formatString: 0
		lineageTag: 927ae949-9f8d-4913-937e-d4bb1fbef7a5
		summarizeBy: sum
		sourceColumn: inactive_players

		annotation SummarizationSetBy = Automatic

	column game_date
		dataType: string
		lineageTag: b6f6bec4-6d7d-4149-a62c-a2b42227bce4
		summarizeBy: none
		sourceColumn: game_date

		annotation SummarizationSetBy = Automatic

	partition mart_rank_daily_summary = m
		mode: import
		source =
				let
				    Source = Odbc.DataSource("dsn=riot_lakehouse_athena", [HierarchicalNavigation=true]),
				    AwsDataCatalog_Database = Source{[Name="AwsDataCatalog",Kind="Database"]}[Data],
				    riot_lakehouse_Schema = AwsDataCatalog_Database{[Name="riot_lakehouse",Kind="Schema"]}[Data],
				    mart_rank_daily_summary_Table = riot_lakehouse_Schema{[Name="mart_rank_daily_summary",Kind="Table"]}[Data]
				in
				    mart_rank_daily_summary_Table

	annotation PBI_ResultType = Table

