-- Riot Lakehouse Gold measures.
-- Paste these into Power BI Desktop after importing the Gold tables.
-- The measures reference only existing Gold tables and columns.

-- Shared / Executive

Matches =
DISTINCTCOUNT('dim_match'[match_id])

Participant Rows =
COUNTROWS('fact_participant_performance')

Unique Players =
DISTINCTCOUNT('fact_participant_performance'[puuid])

Unique Champions =
DISTINCTCOUNT('fact_participant_performance'[champion_id])

Participant Wins =
CALCULATE(
    [Participant Rows],
    'fact_participant_performance'[win] = TRUE()
)

Participant Win Rate =
DIVIDE([Participant Wins], [Participant Rows])

Total Kills =
SUM('fact_participant_performance'[kills])

Total Deaths =
SUM('fact_participant_performance'[deaths])

Total Assists =
SUM('fact_participant_performance'[assists])

KDA Ratio =
DIVIDE([Total Kills] + [Total Assists], [Total Deaths])

Avg KDA =
AVERAGE('fact_participant_performance'[kda])

Avg Gold Earned =
AVERAGE('fact_participant_performance'[gold_earned])

Avg Damage To Champions =
AVERAGE('fact_participant_performance'[total_damage_dealt_to_champions])

Avg Damage Taken =
AVERAGE('fact_participant_performance'[total_damage_taken])

Avg Vision Score =
AVERAGE('fact_participant_performance'[vision_score])

Avg CS =
AVERAGE('fact_participant_performance'[cs])

Avg Match Duration Minutes =
DIVIDE(AVERAGE('dim_match'[game_duration]), 60)

Selected Date Range =
VAR MinDate = MIN('dim_date'[game_date])
VAR MaxDate = MAX('dim_date'[game_date])
RETURN
    IF(
        ISBLANK(MinDate) || ISBLANK(MaxDate),
        "No date selected",
        FORMAT(MinDate, "yyyy-MM-dd") & " to " & FORMAT(MaxDate, "yyyy-MM-dd")
    )

-- Player Performance

Selected Player Label =
COALESCE(
    SELECTEDVALUE('dim_summoner'[riot_id_game_name]),
    SELECTEDVALUE('dim_summoner'[summoner_name]),
    SELECTEDVALUE('dim_summoner'[puuid]),
    "All players"
)

Player Matches =
SUM('mart_player_daily_performance'[matches_played])

Player Wins =
SUM('mart_player_daily_performance'[wins])

Player Losses =
SUM('mart_player_daily_performance'[losses])

Player Win Rate =
DIVIDE([Player Wins], [Player Matches])

Player Total Kills =
SUM('mart_player_daily_performance'[total_kills])

Player Total Deaths =
SUM('mart_player_daily_performance'[total_deaths])

Player Total Assists =
SUM('mart_player_daily_performance'[total_assists])

Player KDA Ratio =
DIVIDE([Player Total Kills] + [Player Total Assists], [Player Total Deaths])

Player Unique Champions =
SUM('mart_player_daily_performance'[unique_champions])

Player Avg Kills =
DIVIDE(
    SUMX(
        'mart_player_daily_performance',
        'mart_player_daily_performance'[avg_kills]
            * 'mart_player_daily_performance'[matches_played]
    ),
    [Player Matches]
)

Player Avg Deaths =
DIVIDE(
    SUMX(
        'mart_player_daily_performance',
        'mart_player_daily_performance'[avg_deaths]
            * 'mart_player_daily_performance'[matches_played]
    ),
    [Player Matches]
)

Player Avg Assists =
DIVIDE(
    SUMX(
        'mart_player_daily_performance',
        'mart_player_daily_performance'[avg_assists]
            * 'mart_player_daily_performance'[matches_played]
    ),
    [Player Matches]
)

Player Avg KDA =
DIVIDE(
    SUMX(
        'mart_player_daily_performance',
        'mart_player_daily_performance'[avg_kda]
            * 'mart_player_daily_performance'[matches_played]
    ),
    [Player Matches]
)

Player Avg Gold Earned =
DIVIDE(
    SUMX(
        'mart_player_daily_performance',
        'mart_player_daily_performance'[avg_gold_earned]
            * 'mart_player_daily_performance'[matches_played]
    ),
    [Player Matches]
)

Player Avg Damage To Champions =
DIVIDE(
    SUMX(
        'mart_player_daily_performance',
        'mart_player_daily_performance'[avg_damage_dealt_to_champions]
            * 'mart_player_daily_performance'[matches_played]
    ),
    [Player Matches]
)

Player Avg Damage Taken =
DIVIDE(
    SUMX(
        'mart_player_daily_performance',
        'mart_player_daily_performance'[avg_damage_taken]
            * 'mart_player_daily_performance'[matches_played]
    ),
    [Player Matches]
)

Player Avg Vision Score =
DIVIDE(
    SUMX(
        'mart_player_daily_performance',
        'mart_player_daily_performance'[avg_vision_score]
            * 'mart_player_daily_performance'[matches_played]
    ),
    [Player Matches]
)

Player Avg CS =
DIVIDE(
    SUMX(
        'mart_player_daily_performance',
        'mart_player_daily_performance'[avg_cs]
            * 'mart_player_daily_performance'[matches_played]
    ),
    [Player Matches]
)

-- Champion Meta

Champion Matches =
SUM('mart_champion_daily_performance'[matches_played])

Champion Unique Players =
SUM('mart_champion_daily_performance'[unique_players])

Champion Wins =
SUM('mart_champion_daily_performance'[wins])

Champion Losses =
SUM('mart_champion_daily_performance'[losses])

Champion Win Rate =
DIVIDE([Champion Wins], [Champion Matches])

Champion Pick Rate =
DIVIDE(
    [Champion Matches],
    CALCULATE([Champion Matches], ALL('dim_champion'))
)

Champion Total Kills =
SUM('mart_champion_daily_performance'[total_kills])

Champion Total Deaths =
SUM('mart_champion_daily_performance'[total_deaths])

Champion Total Assists =
SUM('mart_champion_daily_performance'[total_assists])

Champion Kill Share =
DIVIDE(
    [Champion Total Kills],
    CALCULATE([Champion Total Kills], ALL('dim_champion'))
)

Champion Avg Kills =
DIVIDE(
    SUMX(
        'mart_champion_daily_performance',
        'mart_champion_daily_performance'[avg_kills]
            * 'mart_champion_daily_performance'[matches_played]
    ),
    [Champion Matches]
)

Champion Avg Deaths =
DIVIDE(
    SUMX(
        'mart_champion_daily_performance',
        'mart_champion_daily_performance'[avg_deaths]
            * 'mart_champion_daily_performance'[matches_played]
    ),
    [Champion Matches]
)

Champion Avg Assists =
DIVIDE(
    SUMX(
        'mart_champion_daily_performance',
        'mart_champion_daily_performance'[avg_assists]
            * 'mart_champion_daily_performance'[matches_played]
    ),
    [Champion Matches]
)

Champion Avg KDA =
DIVIDE(
    SUMX(
        'mart_champion_daily_performance',
        'mart_champion_daily_performance'[avg_kda]
            * 'mart_champion_daily_performance'[matches_played]
    ),
    [Champion Matches]
)

Champion Avg Gold Earned =
DIVIDE(
    SUMX(
        'mart_champion_daily_performance',
        'mart_champion_daily_performance'[avg_gold_earned]
            * 'mart_champion_daily_performance'[matches_played]
    ),
    [Champion Matches]
)

Champion Avg Damage To Champions =
DIVIDE(
    SUMX(
        'mart_champion_daily_performance',
        'mart_champion_daily_performance'[avg_damage_dealt_to_champions]
            * 'mart_champion_daily_performance'[matches_played]
    ),
    [Champion Matches]
)

Champion Damage Share =
DIVIDE(
    SUMX(
        'mart_champion_daily_performance',
        'mart_champion_daily_performance'[avg_damage_dealt_to_champions]
            * 'mart_champion_daily_performance'[matches_played]
    ),
    CALCULATE(
        SUMX(
            'mart_champion_daily_performance',
            'mart_champion_daily_performance'[avg_damage_dealt_to_champions]
                * 'mart_champion_daily_performance'[matches_played]
        ),
        ALL('dim_champion')
    )
)

Champion Avg Damage Taken =
DIVIDE(
    SUMX(
        'mart_champion_daily_performance',
        'mart_champion_daily_performance'[avg_damage_taken]
            * 'mart_champion_daily_performance'[matches_played]
    ),
    [Champion Matches]
)

Champion Avg Vision Score =
DIVIDE(
    SUMX(
        'mart_champion_daily_performance',
        'mart_champion_daily_performance'[avg_vision_score]
            * 'mart_champion_daily_performance'[matches_played]
    ),
    [Champion Matches]
)

Champion Avg CS =
DIVIDE(
    SUMX(
        'mart_champion_daily_performance',
        'mart_champion_daily_performance'[avg_cs]
            * 'mart_champion_daily_performance'[matches_played]
    ),
    [Champion Matches]
)

Champion Meta Score =
VAR PickComponent = [Champion Pick Rate]
VAR WinComponent = [Champion Win Rate]
VAR KdaBaseline = CALCULATE([Champion Avg KDA], ALL('dim_champion'))
VAR KdaComponent = DIVIDE([Champion Avg KDA], KdaBaseline)
RETURN
    (PickComponent * 0.45)
        + (WinComponent * 0.35)
        + (KdaComponent * 0.20)

-- Role / Lane Analysis

Role Matches =
SUM('mart_role_daily_performance'[matches_played])

Role Unique Players =
SUM('mart_role_daily_performance'[unique_players])

Role Unique Champions =
SUM('mart_role_daily_performance'[unique_champions])

Role Wins =
SUM('mart_role_daily_performance'[wins])

Role Losses =
SUM('mart_role_daily_performance'[losses])

Role Win Rate =
DIVIDE([Role Wins], [Role Matches])

Role Pick Share =
DIVIDE(
    [Role Matches],
    CALCULATE([Role Matches], ALL('mart_role_daily_performance'[team_position]))
)

Role Avg Kills =
DIVIDE(
    SUMX(
        'mart_role_daily_performance',
        'mart_role_daily_performance'[avg_kills]
            * 'mart_role_daily_performance'[matches_played]
    ),
    [Role Matches]
)

Role Avg Deaths =
DIVIDE(
    SUMX(
        'mart_role_daily_performance',
        'mart_role_daily_performance'[avg_deaths]
            * 'mart_role_daily_performance'[matches_played]
    ),
    [Role Matches]
)

Role Avg Assists =
DIVIDE(
    SUMX(
        'mart_role_daily_performance',
        'mart_role_daily_performance'[avg_assists]
            * 'mart_role_daily_performance'[matches_played]
    ),
    [Role Matches]
)

Role Avg KDA =
DIVIDE(
    SUMX(
        'mart_role_daily_performance',
        'mart_role_daily_performance'[avg_kda]
            * 'mart_role_daily_performance'[matches_played]
    ),
    [Role Matches]
)

Role Avg Gold Earned =
DIVIDE(
    SUMX(
        'mart_role_daily_performance',
        'mart_role_daily_performance'[avg_gold_earned]
            * 'mart_role_daily_performance'[matches_played]
    ),
    [Role Matches]
)

Role Avg Damage To Champions =
DIVIDE(
    SUMX(
        'mart_role_daily_performance',
        'mart_role_daily_performance'[avg_damage_dealt_to_champions]
            * 'mart_role_daily_performance'[matches_played]
    ),
    [Role Matches]
)

Role Avg Damage Taken =
DIVIDE(
    SUMX(
        'mart_role_daily_performance',
        'mart_role_daily_performance'[avg_damage_taken]
            * 'mart_role_daily_performance'[matches_played]
    ),
    [Role Matches]
)

Role Avg Vision Score =
DIVIDE(
    SUMX(
        'mart_role_daily_performance',
        'mart_role_daily_performance'[avg_vision_score]
            * 'mart_role_daily_performance'[matches_played]
    ),
    [Role Matches]
)

Role Avg CS =
DIVIDE(
    SUMX(
        'mart_role_daily_performance',
        'mart_role_daily_performance'[avg_cs]
            * 'mart_role_daily_performance'[matches_played]
    ),
    [Role Matches]
)

-- Rank Snapshot

Rank Summary Players =
VAR RankFilter =
    SUMMARIZE(
        'dim_rank',
        'dim_rank'[queue],
        'dim_rank'[tier],
        'dim_rank'[rank]
    )
RETURN
    CALCULATE(
        SUM('mart_rank_daily_summary'[players]),
        TREATAS(
            RankFilter,
            'mart_rank_daily_summary'[queue],
            'mart_rank_daily_summary'[tier],
            'mart_rank_daily_summary'[rank]
        )
    )

Rank Population Share =
DIVIDE(
    [Rank Summary Players],
    CALCULATE([Rank Summary Players], ALL('dim_rank'))
)

Rank Avg League Points =
VAR RankFilter =
    SUMMARIZE(
        'dim_rank',
        'dim_rank'[queue],
        'dim_rank'[tier],
        'dim_rank'[rank]
    )
RETURN
    CALCULATE(
        DIVIDE(
            SUMX(
                'mart_rank_daily_summary',
                'mart_rank_daily_summary'[avg_league_points]
                    * 'mart_rank_daily_summary'[players]
            ),
            SUM('mart_rank_daily_summary'[players])
        ),
        TREATAS(
            RankFilter,
            'mart_rank_daily_summary'[queue],
            'mart_rank_daily_summary'[tier],
            'mart_rank_daily_summary'[rank]
        )
    )

Rank Avg Win Rate =
VAR RankFilter =
    SUMMARIZE(
        'dim_rank',
        'dim_rank'[queue],
        'dim_rank'[tier],
        'dim_rank'[rank]
    )
RETURN
    CALCULATE(
        DIVIDE(
            SUMX(
                'mart_rank_daily_summary',
                'mart_rank_daily_summary'[avg_win_rate]
                    * 'mart_rank_daily_summary'[players]
            ),
            SUM('mart_rank_daily_summary'[players])
        ),
        TREATAS(
            RankFilter,
            'mart_rank_daily_summary'[queue],
            'mart_rank_daily_summary'[tier],
            'mart_rank_daily_summary'[rank]
        )
    )

Rank Total Wins =
VAR RankFilter =
    SUMMARIZE(
        'dim_rank',
        'dim_rank'[queue],
        'dim_rank'[tier],
        'dim_rank'[rank]
    )
RETURN
    CALCULATE(
        SUM('mart_rank_daily_summary'[total_wins]),
        TREATAS(
            RankFilter,
            'mart_rank_daily_summary'[queue],
            'mart_rank_daily_summary'[tier],
            'mart_rank_daily_summary'[rank]
        )
    )

Rank Total Losses =
VAR RankFilter =
    SUMMARIZE(
        'dim_rank',
        'dim_rank'[queue],
        'dim_rank'[tier],
        'dim_rank'[rank]
    )
RETURN
    CALCULATE(
        SUM('mart_rank_daily_summary'[total_losses]),
        TREATAS(
            RankFilter,
            'mart_rank_daily_summary'[queue],
            'mart_rank_daily_summary'[tier],
            'mart_rank_daily_summary'[rank]
        )
    )

Hot Streak Players =
VAR RankFilter =
    SUMMARIZE(
        'dim_rank',
        'dim_rank'[queue],
        'dim_rank'[tier],
        'dim_rank'[rank]
    )
RETURN
    CALCULATE(
        SUM('mart_rank_daily_summary'[hot_streak_players]),
        TREATAS(
            RankFilter,
            'mart_rank_daily_summary'[queue],
            'mart_rank_daily_summary'[tier],
            'mart_rank_daily_summary'[rank]
        )
    )

Veteran Players =
VAR RankFilter =
    SUMMARIZE(
        'dim_rank',
        'dim_rank'[queue],
        'dim_rank'[tier],
        'dim_rank'[rank]
    )
RETURN
    CALCULATE(
        SUM('mart_rank_daily_summary'[veteran_players]),
        TREATAS(
            RankFilter,
            'mart_rank_daily_summary'[queue],
            'mart_rank_daily_summary'[tier],
            'mart_rank_daily_summary'[rank]
        )
    )

Fresh Blood Players =
VAR RankFilter =
    SUMMARIZE(
        'dim_rank',
        'dim_rank'[queue],
        'dim_rank'[tier],
        'dim_rank'[rank]
    )
RETURN
    CALCULATE(
        SUM('mart_rank_daily_summary'[fresh_blood_players]),
        TREATAS(
            RankFilter,
            'mart_rank_daily_summary'[queue],
            'mart_rank_daily_summary'[tier],
            'mart_rank_daily_summary'[rank]
        )
    )

Inactive Players =
VAR RankFilter =
    SUMMARIZE(
        'dim_rank',
        'dim_rank'[queue],
        'dim_rank'[tier],
        'dim_rank'[rank]
    )
RETURN
    CALCULATE(
        SUM('mart_rank_daily_summary'[inactive_players]),
        TREATAS(
            RankFilter,
            'mart_rank_daily_summary'[queue],
            'mart_rank_daily_summary'[tier],
            'mart_rank_daily_summary'[rank]
        )
    )

Rank Snapshot Unique Players =
VAR RankFilter =
    SUMMARIZE(
        'dim_rank',
        'dim_rank'[queue],
        'dim_rank'[tier],
        'dim_rank'[rank]
    )
RETURN
    CALCULATE(
        DISTINCTCOUNT('fact_rank_snapshot'[puuid]),
        TREATAS(
            RankFilter,
            'fact_rank_snapshot'[queue],
            'fact_rank_snapshot'[tier],
            'fact_rank_snapshot'[rank]
        )
    )

Average League Points =
VAR RankFilter =
    SUMMARIZE(
        'dim_rank',
        'dim_rank'[queue],
        'dim_rank'[tier],
        'dim_rank'[rank]
    )
RETURN
    CALCULATE(
        AVERAGE('fact_rank_snapshot'[league_points]),
        TREATAS(
            RankFilter,
            'fact_rank_snapshot'[queue],
            'fact_rank_snapshot'[tier],
            'fact_rank_snapshot'[rank]
        )
    )

Rank Snapshot Wins =
VAR RankFilter =
    SUMMARIZE(
        'dim_rank',
        'dim_rank'[queue],
        'dim_rank'[tier],
        'dim_rank'[rank]
    )
RETURN
    CALCULATE(
        SUM('fact_rank_snapshot'[wins]),
        TREATAS(
            RankFilter,
            'fact_rank_snapshot'[queue],
            'fact_rank_snapshot'[tier],
            'fact_rank_snapshot'[rank]
        )
    )

Rank Snapshot Losses =
VAR RankFilter =
    SUMMARIZE(
        'dim_rank',
        'dim_rank'[queue],
        'dim_rank'[tier],
        'dim_rank'[rank]
    )
RETURN
    CALCULATE(
        SUM('fact_rank_snapshot'[losses]),
        TREATAS(
            RankFilter,
            'fact_rank_snapshot'[queue],
            'fact_rank_snapshot'[tier],
            'fact_rank_snapshot'[rank]
        )
    )

Rank Snapshot Win Rate =
DIVIDE([Rank Snapshot Wins], [Rank Snapshot Wins] + [Rank Snapshot Losses])

Is Hot Streak Count =
CALCULATE(
    [Rank Snapshot Unique Players],
    'fact_rank_snapshot'[hot_streak] = TRUE()
)

Is Inactive Count =
CALCULATE(
    [Rank Snapshot Unique Players],
    'fact_rank_snapshot'[inactive] = TRUE()
)

-- Team Objectives

Team Objective Games =
SUM('mart_team_objective_daily_summary'[games_played])

Team Wins =
SUM('mart_team_objective_daily_summary'[wins])

Team Losses =
SUM('mart_team_objective_daily_summary'[losses])

Team Win Rate =
DIVIDE([Team Wins], [Team Objective Games])

Total Objective Score =
SUM('fact_team_objectives'[objective_score])

Team Objective Score =
[Total Objective Score]

Objective Rows =
COUNTROWS('fact_team_objectives')

Avg Objectives Per Team Game =
DIVIDE([Total Objective Score], [Objective Rows])

Avg Objective Score =
DIVIDE(
    SUMX(
        'mart_team_objective_daily_summary',
        'mart_team_objective_daily_summary'[avg_objective_score]
            * 'mart_team_objective_daily_summary'[games_played]
    ),
    [Team Objective Games]
)

Objective Control Share =
DIVIDE(
    [Total Objective Score],
    CALCULATE([Total Objective Score], ALL('dim_team'))
)

Total Baron Kills =
SUM('fact_team_objectives'[baron_kills])

Total Dragon Kills =
SUM('fact_team_objectives'[dragon_kills])

Total Rift Herald Kills =
SUM('fact_team_objectives'[rift_herald_kills])

Total Tower Kills =
SUM('fact_team_objectives'[tower_kills])

Total Inhibitor Kills =
SUM('fact_team_objectives'[inhibitor_kills])

Total Champion Kills =
SUM('fact_team_objectives'[champion_kills])

Avg Baron Kills =
DIVIDE(
    SUMX(
        'mart_team_objective_daily_summary',
        'mart_team_objective_daily_summary'[avg_baron_kills]
            * 'mart_team_objective_daily_summary'[games_played]
    ),
    [Team Objective Games]
)

Avg Dragon Kills =
DIVIDE(
    SUMX(
        'mart_team_objective_daily_summary',
        'mart_team_objective_daily_summary'[avg_dragon_kills]
            * 'mart_team_objective_daily_summary'[games_played]
    ),
    [Team Objective Games]
)

Avg Rift Herald Kills =
DIVIDE(
    SUMX(
        'mart_team_objective_daily_summary',
        'mart_team_objective_daily_summary'[avg_rift_herald_kills]
            * 'mart_team_objective_daily_summary'[games_played]
    ),
    [Team Objective Games]
)

Avg Tower Kills =
DIVIDE(
    SUMX(
        'mart_team_objective_daily_summary',
        'mart_team_objective_daily_summary'[avg_tower_kills]
            * 'mart_team_objective_daily_summary'[games_played]
    ),
    [Team Objective Games]
)

Avg Inhibitor Kills =
DIVIDE(
    SUMX(
        'mart_team_objective_daily_summary',
        'mart_team_objective_daily_summary'[avg_inhibitor_kills]
            * 'mart_team_objective_daily_summary'[games_played]
    ),
    [Team Objective Games]
)

Avg Champion Kills =
DIVIDE(
    SUMX(
        'mart_team_objective_daily_summary',
        'mart_team_objective_daily_summary'[avg_champion_kills]
            * 'mart_team_objective_daily_summary'[games_played]
    ),
    [Team Objective Games]
)

-- Timeline Events

Timeline Frames =
COUNTROWS('fact_timeline_frames')

Timeline Frame Event Count =
SUM('fact_timeline_frames'[event_count])

Timeline Events =
COUNTROWS('fact_timeline_events')

Timeline Event Match Count =
DISTINCTCOUNT('fact_timeline_events'[match_id])

Avg Events Per Match =
DIVIDE([Timeline Events], [Timeline Event Match Count])

Avg Events Per Frame =
DIVIDE([Timeline Events], [Timeline Frames])

Average Event Minute =
DIVIDE(AVERAGE('fact_timeline_events'[event_timestamp]), 60000)

Kill Events =
CALCULATE(
    [Timeline Events],
    'fact_timeline_events'[event_type] = "CHAMPION_KILL"
)

Elite Monster Events =
CALCULATE(
    [Timeline Events],
    'fact_timeline_events'[event_type] = "ELITE_MONSTER_KILL"
)

Building Events =
CALCULATE(
    [Timeline Events],
    'fact_timeline_events'[event_type] = "BUILDING_KILL"
)

Dragon Events =
CALCULATE(
    [Timeline Events],
    'fact_timeline_events'[monster_type] = "DRAGON"
)

Baron Events =
CALCULATE(
    [Timeline Events],
    'fact_timeline_events'[monster_type] = "BARON_NASHOR"
)

Rift Herald Events =
CALCULATE(
    [Timeline Events],
    'fact_timeline_events'[monster_type] = "RIFTHERALD"
)

Tower Events =
CALCULATE(
    [Timeline Events],
    'fact_timeline_events'[building_type] = "TOWER_BUILDING"
)

Inhibitor Events =
CALCULATE(
    [Timeline Events],
    'fact_timeline_events'[building_type] = "INHIBITOR_BUILDING"
)

Events Before 15 Minutes =
CALCULATE(
    [Timeline Events],
    'fact_timeline_events'[event_timestamp] <= 900000
)

Kills Before 15 Minutes =
CALCULATE(
    [Kill Events],
    'fact_timeline_events'[event_timestamp] <= 900000
)
