def table_definitions() -> dict[str, list[str]]:
    return {
        "bronze_raw_json": ["dataset", "source_file", "file_hash", "ingest_ts", "payload_json"],
        "silver_matches": [
            "match_id",
            "game_id",
            "platform_id",
            "queue_id",
            "game_mode",
            "game_type",
            "game_version",
            "game_creation",
            "game_start_timestamp",
            "game_end_timestamp",
            "game_duration",
            "participant_count",
        ],
        "silver_participants": [
            "match_id",
            "puuid",
            "summoner_id",
            "riot_id_game_name",
            "champion_id",
            "champion_name",
            "team_id",
            "team_position",
            "lane",
            "role",
            "win",
            "kills",
            "deaths",
            "assists",
            "gold_earned",
            "total_damage_dealt_to_champions",
            "vision_score",
            "total_minions_killed",
        ],
        "silver_teams": [
            "match_id",
            "team_id",
            "win",
            "baron_kills",
            "dragon_kills",
            "rift_herald_kills",
            "tower_kills",
            "inhibitor_kills",
        ],
        "silver_summoners": ["puuid", "profile_icon_id", "revision_date", "summoner_level"],
        "silver_ranked": [
            "league_id",
            "queue",
            "tier",
            "rank",
            "puuid",
            "league_points",
            "wins",
            "losses",
            "hot_streak",
            "veteran",
            "fresh_blood",
            "inactive",
        ],
        "silver_timeline_frames": [
            "match_id",
            "frame_index",
            "timestamp",
            "participant_frame_count",
            "event_count",
        ],
        "silver_timeline_events": [
            "match_id",
            "frame_index",
            "event_index",
            "timestamp",
            "type",
            "participant_id",
            "killer_id",
            "victim_id",
            "team_id",
            "monster_type",
            "building_type",
        ],
    }
