from __future__ import annotations

from typing import Any


DIMENSION_TABLES = [
    "dim_date",
    "dim_match",
    "dim_summoner",
    "dim_champion",
    "dim_team",
    "dim_rank",
]

FACT_TABLES = [
    "fact_participant_performance",
    "fact_team_objectives",
    "fact_rank_snapshot",
    "fact_timeline_frames",
    "fact_timeline_events",
]

MART_TABLES = [
    "mart_player_daily_performance",
    "mart_champion_daily_performance",
    "mart_role_daily_performance",
    "mart_rank_daily_summary",
    "mart_team_objective_daily_summary",
]

GOLD_TABLES = [*DIMENSION_TABLES, *FACT_TABLES, *MART_TABLES]

GOLD_COLUMNS = {
    "dim_date": [
        "date_key",
        "game_date",
        "date_year",
        "date_month",
        "date_day",
        "day_of_week",
    ],
    "dim_match": [
        "match_id",
        "game_id",
        "platform_id",
        "queue_id",
        "game_mode",
        "game_type",
        "game_version",
        "game_creation",
        "game_start_timestamp",
        "game_end_timestamp",
        "game_duration",
        "participant_count",
        "game_date",
    ],
    "dim_summoner": [
        "puuid",
        "summoner_id",
        "account_id",
        "summoner_name",
        "riot_id_game_name",
        "riot_id_tagline",
        "profile_icon_id",
        "revision_date",
        "summoner_level",
        "first_seen_game_date",
        "last_seen_game_date",
    ],
    "dim_champion": [
        "champion_id",
        "champion_name",
        "first_seen_game_date",
        "last_seen_game_date",
    ],
    "dim_team": [
        "team_id",
        "team_side",
        "first_seen_game_date",
        "last_seen_game_date",
    ],
    "dim_rank": [
        "queue",
        "tier",
        "rank",
        "rank_order",
    ],
    "fact_participant_performance": [
        "game_date",
        "match_id",
        "participant_id",
        "puuid",
        "summoner_id",
        "champion_id",
        "team_id",
        "team_position",
        "win",
        "kills",
        "deaths",
        "assists",
        "kda",
        "gold_earned",
        "total_damage_dealt_to_champions",
        "total_damage_taken",
        "vision_score",
        "total_minions_killed",
        "neutral_minions_killed",
        "cs",
    ],
    "fact_team_objectives": [
        "game_date",
        "match_id",
        "team_id",
        "team_side",
        "win",
        "baron_kills",
        "dragon_kills",
        "rift_herald_kills",
        "tower_kills",
        "inhibitor_kills",
        "champion_kills",
        "objective_score",
    ],
    "fact_rank_snapshot": [
        "game_date",
        "puuid",
        "summoner_id",
        "queue",
        "tier",
        "rank",
        "league_points",
        "wins",
        "losses",
        "win_rate",
        "hot_streak",
        "veteran",
        "fresh_blood",
        "inactive",
    ],
    "fact_timeline_frames": [
        "game_date",
        "match_id",
        "frame_index",
        "frame_timestamp",
        "participant_frame_count",
        "event_count",
    ],
    "fact_timeline_events": [
        "game_date",
        "match_id",
        "frame_index",
        "event_index",
        "event_timestamp",
        "event_type",
        "participant_id",
        "killer_id",
        "victim_id",
        "team_id",
        "monster_type",
        "building_type",
        "lane_type",
    ],
    "mart_player_daily_performance": [
        "game_date",
        "puuid",
        "summoner_id",
        "summoner_name",
        "riot_id_game_name",
        "riot_id_tagline",
        "matches_played",
        "wins",
        "losses",
        "win_rate",
        "unique_champions",
        "total_kills",
        "total_deaths",
        "total_assists",
        "avg_kills",
        "avg_deaths",
        "avg_assists",
        "avg_kda",
        "avg_gold_earned",
        "avg_damage_dealt_to_champions",
        "avg_damage_taken",
        "avg_vision_score",
        "avg_cs",
    ],
    "mart_champion_daily_performance": [
        "game_date",
        "champion_id",
        "champion_name",
        "matches_played",
        "unique_players",
        "wins",
        "losses",
        "win_rate",
        "total_kills",
        "total_deaths",
        "total_assists",
        "avg_kills",
        "avg_deaths",
        "avg_assists",
        "avg_kda",
        "avg_gold_earned",
        "avg_damage_dealt_to_champions",
        "avg_damage_taken",
        "avg_vision_score",
        "avg_cs",
    ],
    "mart_role_daily_performance": [
        "game_date",
        "team_position",
        "matches_played",
        "unique_players",
        "unique_champions",
        "wins",
        "losses",
        "win_rate",
        "avg_kills",
        "avg_deaths",
        "avg_assists",
        "avg_kda",
        "avg_gold_earned",
        "avg_damage_dealt_to_champions",
        "avg_damage_taken",
        "avg_vision_score",
        "avg_cs",
    ],
    "mart_rank_daily_summary": [
        "game_date",
        "queue",
        "tier",
        "rank",
        "players",
        "avg_league_points",
        "total_wins",
        "total_losses",
        "avg_win_rate",
        "hot_streak_players",
        "veteran_players",
        "fresh_blood_players",
        "inactive_players",
    ],
    "mart_team_objective_daily_summary": [
        "game_date",
        "team_id",
        "team_side",
        "games_played",
        "wins",
        "losses",
        "win_rate",
        "avg_baron_kills",
        "avg_dragon_kills",
        "avg_rift_herald_kills",
        "avg_tower_kills",
        "avg_inhibitor_kills",
        "avg_champion_kills",
        "avg_objective_score",
    ],
}

BOOLEAN_COLUMNS = {
    "win",
    "hot_streak",
    "veteran",
    "fresh_blood",
    "inactive",
}

STRING_COLUMNS = {
    "date_key",
    "game_date",
    "first_seen_game_date",
    "last_seen_game_date",
    "match_id",
    "platform_id",
    "game_mode",
    "game_type",
    "game_version",
    "puuid",
    "summoner_id",
    "account_id",
    "summoner_name",
    "riot_id_game_name",
    "riot_id_tagline",
    "champion_name",
    "team_side",
    "team_position",
    "queue",
    "tier",
    "rank",
    "event_type",
    "monster_type",
    "building_type",
    "lane_type",
}

LONG_COLUMNS = {
    "date_year",
    "date_month",
    "date_day",
    "day_of_week",
    "game_id",
    "queue_id",
    "game_creation",
    "game_start_timestamp",
    "game_end_timestamp",
    "game_duration",
    "participant_count",
    "profile_icon_id",
    "revision_date",
    "summoner_level",
    "champion_id",
    "team_id",
    "rank_order",
    "participant_id",
    "kills",
    "deaths",
    "assists",
    "gold_earned",
    "total_damage_dealt_to_champions",
    "total_damage_taken",
    "vision_score",
    "total_minions_killed",
    "neutral_minions_killed",
    "cs",
    "baron_kills",
    "dragon_kills",
    "rift_herald_kills",
    "tower_kills",
    "inhibitor_kills",
    "champion_kills",
    "objective_score",
    "frame_index",
    "frame_timestamp",
    "participant_frame_count",
    "event_count",
    "event_index",
    "event_timestamp",
    "killer_id",
    "victim_id",
    "league_points",
    "matches_played",
    "games_played",
    "wins",
    "losses",
    "unique_champions",
    "unique_players",
    "players",
    "total_kills",
    "total_deaths",
    "total_assists",
    "total_wins",
    "total_losses",
    "hot_streak_players",
    "veteran_players",
    "fresh_blood_players",
    "inactive_players",
}

DOUBLE_COLUMNS = {
    "kda",
    "win_rate",
    "avg_kills",
    "avg_deaths",
    "avg_assists",
    "avg_kda",
    "avg_gold_earned",
    "avg_damage_dealt_to_champions",
    "avg_damage_taken",
    "avg_vision_score",
    "avg_cs",
    "avg_league_points",
    "avg_win_rate",
    "avg_baron_kills",
    "avg_dragon_kills",
    "avg_rift_herald_kills",
    "avg_tower_kills",
    "avg_inhibitor_kills",
    "avg_champion_kills",
    "avg_objective_score",
}


def gold_schema(table: str) -> Any:
    from pyspark.sql.types import (
        BooleanType,
        DoubleType,
        LongType,
        StringType,
        StructField,
        StructType,
    )

    if table not in GOLD_COLUMNS:
        raise ValueError(f"Unknown gold table: {table}")

    fields = []
    for column in GOLD_COLUMNS[table]:
        if column in BOOLEAN_COLUMNS:
            data_type = BooleanType()
        elif column in STRING_COLUMNS:
            data_type = StringType()
        elif column in LONG_COLUMNS:
            data_type = LongType()
        elif column in DOUBLE_COLUMNS:
            data_type = DoubleType()
        else:
            raise ValueError(f"No Gold schema type configured for column: {column}")
        fields.append(StructField(column, data_type, nullable=True))
    return StructType(fields)
